"""BookTok - Telegram bot for delivering book learning snippets."""

from booktok.models import (
    Book,
    BookStatus,
    DeliverySchedule,
    FileType,
    Frequency,
    Snippet,
    User,
    UserProgress,
    ValidationError,
)
from booktok.book_processor import (
    BookProcessor,
    BookProcessingError,
    InvalidFileError,
    ProcessingResult,
    UnsupportedFileTypeError,
)
from booktok.book_scanner import (
    BookFile,
    BookScanner,
)
from booktok.snippet_generator import (
    SnippetGenerator,
    SnippetGenerationError,
    SnippetGenerationResult,
)
from booktok.snippet_formatter import (
    FormattedMessage,
    FormattedSnippet,
    SnippetFormatter,
    validate_message_length,
    get_safe_content_length,
)
from booktok.telegram_bot import (
    TelegramBotInterface,
    WELCOME_MESSAGE,
    HELP_MESSAGE,
)
from booktok.delivery_scheduler import (
    AutomatedDeliveryRunner,
    DeliveryResult,
    DeliveryScheduler,
    ScheduleInfo,
    SchedulerError,
    InvalidTimezoneError,
    InvalidScheduleError,
    UserNotFoundError,
    BookNotFoundError,
)
from booktok.input_validator import (
    sanitize_text,
    sanitize_filename,
    validate_telegram_id,
    validate_book_title,
    validate_author,
    sanitize_for_markdown,
    validate_message_text,
    ValidationError as InputValidationError,
)
from booktok.database import (
    initialize_database,
    create_tables,
    close_database,
    check_database_integrity,
    recover_database,
    get_database_path,
    DatabaseError,
    DatabaseConnectionError,
    DatabaseIntegrityError,
    DatabaseCorruptedError,
)
from booktok.config import (
    AppConfig,
    BooksConfig,
    DatabaseConfig,
    TelegramConfig,
    SchedulerConfig,
    LoggingConfig,
    load_config,
    setup_logging,
    validate_config,
)


def main() -> None:
    print("Hello from booktok!")


__all__ = [
    "AppConfig",
    "AutomatedDeliveryRunner",
    "Book",
    "BookFile",
    "BookNotFoundError",
    "BookProcessor",
    "BookProcessingError",
    "BookScanner",
    "BooksConfig",
    "BookStatus",
    "check_database_integrity",
    "close_database",
    "create_tables",
    "DatabaseConfig",
    "DatabaseConnectionError",
    "DatabaseCorruptedError",
    "DatabaseError",
    "DatabaseIntegrityError",
    "DeliveryResult",
    "DeliverySchedule",
    "DeliveryScheduler",
    "FileType",
    "FormattedMessage",
    "FormattedSnippet",
    "Frequency",
    "get_database_path",
    "get_safe_content_length",
    "HELP_MESSAGE",
    "initialize_database",
    "InputValidationError",
    "InvalidFileError",
    "InvalidScheduleError",
    "InvalidTimezoneError",
    "load_config",
    "LoggingConfig",
    "main",
    "ProcessingResult",
    "recover_database",
    "ScheduleInfo",
    "SchedulerConfig",
    "SchedulerError",
    "sanitize_filename",
    "sanitize_for_markdown",
    "sanitize_text",
    "SchedulerConfig",
    "setup_logging",
    "Snippet",
    "SnippetFormatter",
    "SnippetGenerationError",
    "SnippetGenerationResult",
    "SnippetGenerator",
    "TelegramBotInterface",
    "TelegramConfig",
    "UnsupportedFileTypeError",
    "User",
    "UserNotFoundError",
    "UserProgress",
    "validate_author",
    "validate_book_title",
    "validate_config",
    "validate_message_length",
    "validate_message_text",
    "validate_telegram_id",
    "ValidationError",
    "WELCOME_MESSAGE",
]
